fix: conflict resolution
tkey/tkey-mpc-swift pull request #7
Opened 2023-08-21 06:44 UTC by metalurgical

2023-08-24 10:30 UTC, himanshuchawla009 requested changes

2023-08-24 10:30 UTC, himanshuchawla009 commented on Sources/ThresholdKey/ThresholdKey.swift
> +    private func initialize(import_share: String?, input: ShareStore?, never_initialize_new_key: Bool?, include_local_metadata_transitions: Bool?, delete_1_of_1 : Bool = false, use_tss: Bool = false,
we shouldn't include delete_1_of_1 in mpc version, it will never be used coz mpc accounts are always on mfa.  We should just pass value as false to underlying rust function but should not expose this flag to developer.

2023-08-24 15:24 UTC, metalurgical commented on Sources/ThresholdKey/ThresholdKey.swift
> +    private func initialize(import_share: String?, input: ShareStore?, never_initialize_new_key: Bool?, include_local_metadata_transitions: Bool?, delete_1_of_1 : Bool = false, use_tss: Bool = false,
Sure we can do that. However what if they are coming directly from the SFA flow straight to MPC and skipping MFA in between?

2023-08-25 03:16 UTC, himanshuchawla009 commented on Sources/ThresholdKey/ThresholdKey.swift
> +    private func initialize(import_share: String?, input: ShareStore?, never_initialize_new_key: Bool?, include_local_metadata_transitions: Bool?, delete_1_of_1 : Bool = false, use_tss: Bool = false,
this flow won't work for sfa to mpc , this is only intended to work for sfa to mpc, reason sfa key is reconstructed but mpc key is never so this flow it not for sfa to mpc.

2023-08-25 03:20 UTC, metalurgical commented on Sources/ThresholdKey/ThresholdKey.swift
> +    private func initialize(import_share: String?, input: ShareStore?, never_initialize_new_key: Bool?, include_local_metadata_transitions: Bool?, delete_1_of_1 : Bool = false, use_tss: Bool = false,
Removed parameter

2023-08-25 03:27 UTC, himanshuchawla009 approved these changes
lgtm

2023-08-25 03:28 UTC, merged